<a href="https://colab.research.google.com/github/AbhinavKumar0000/Machine_learning/blob/main/tf_data_pipline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
lst = [1,2,3,2,1,3,3423,423,424,2]

In [3]:
tf_dataset= tf.data.Dataset.from_tensor_slices(lst)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [7]:
for num in tf_dataset.as_numpy_iterator():
  print(num)

1
2
3
2
1
3
3423
423
424
2


In [8]:
for num in tf_dataset.take(3):
  print(num.numpy())

1
2
3


In [11]:
tf_dataset = tf_dataset.filter(lambda x: x>5)
for num in tf_dataset.as_numpy_iterator():
  print(num)

3423
423
424


In [12]:
tf_dataset = tf_dataset.map(lambda x: x*5)
for num in tf_dataset.as_numpy_iterator():
  print(num)

17115
2115
2120


In [15]:
tf_dataset = tf_dataset.shuffle(1)
for num in tf_dataset.as_numpy_iterator():
  print(num)

2115
17115
2120


In [19]:
for batch in tf_dataset.batch(3):
  print(batch.numpy())

[ 2115  2120 17115]


In [22]:
tf_dataset= tf.data.Dataset.from_tensor_slices(lst)
final_pipeline = tf_dataset.filter(lambda x: x>5).map(lambda y: y*5).shuffle(1).batch(3)

for num in tf_dataset.as_numpy_iterator():
  print(num)

print("--------------------------")

for num in final_pipeline.as_numpy_iterator():
  print(num)

1
2
3
2
1
3
3423
423
424
2
--------------------------
[17115  2115  2120]


In [49]:
image_ds = tf.data.Dataset.list_files('/content/drive/MyDrive/dataset_images/*/*', shuffle =False)

In [50]:
for filr in image_ds.take(5):
  print(filr.numpy())

b'/content/drive/MyDrive/dataset_images/f1_car/031325-f1-trailer-announcement-inline-image-01-67d33e2261917.jpg'
b'/content/drive/MyDrive/dataset_images/f1_car/108060339-Inside_Track_Thumbnail_1_CLEAN.jpg'
b'/content/drive/MyDrive/dataset_images/f1_car/112496843.jpg'
b'/content/drive/MyDrive/dataset_images/f1_car/118842794.jpg'
b'/content/drive/MyDrive/dataset_images/f1_car/11sp-brazil-sprint-inyt1-mediumSquareAt3X.jpg'


In [51]:
class_names = ["f1_car", "fighter_jet"]

In [52]:
image_count = len(image_ds)
image_count

199

In [53]:
train_size = int(image_count*0.8)

train_ds = image_ds.take(train_size)
test_ds = image_ds.skip(train_size)

In [36]:
len(test_ds)

40

In [37]:
len(train_ds)

159

In [57]:
label = "b'/content/drive/MyDrive/dataset_images/f1_car/031325-f1-trailer-announcement-inline-image-01-67d33e2261917.jpg'"

label.split("/")[-2]

'f1_car'

In [60]:
def get_label(file_path):
  return tf.strings.split(file_path,"/")[-2]

In [62]:
def process_image(file_path):
  label = get_label(file_path)

  img = tf.io.read_file(file_path)
  img = tf.image.decode_jpeg(img)
  img = tf.image.resize(img,[128,128])

  return img, label

In [67]:
train_ds = train_ds.map(process_image)
for label in train_ds.take(3):
  print(label)

(<tf.Tensor: shape=(128, 128, 3), dtype=float32, numpy=
array([[[ 54.398438,  68.39844 ,  69.39844 ],
        [ 54.      ,  68.      ,  69.      ],
        [ 54.5     ,  68.5     ,  70.484375],
        ...,
        [ 36.      ,  53.      ,  60.      ],
        [ 37.      ,  54.      ,  61.      ],
        [ 35.601562,  52.601562,  59.601562]],

       [[ 55.      ,  69.      ,  70.      ],
        [ 54.      ,  68.      ,  71.      ],
        [ 53.5     ,  67.5     ,  69.515625],
        ...,
        [ 37.      ,  54.      ,  61.      ],
        [ 36.5     ,  53.5     ,  60.5     ],
        [ 37.05078 ,  54.05078 ,  61.05078 ]],

       [[ 54.94922 ,  68.94922 ,  69.94922 ],
        [ 55.      ,  69.      ,  72.      ],
        [ 54.476562,  68.47656 ,  68.96875 ],
        ...,
        [ 37.746094,  54.746094,  61.746094],
        [ 37.      ,  54.      ,  61.      ],
        [ 38.      ,  55.      ,  62.      ]],

       ...,

       [[ 85.      ,  91.      ,  81.      ],
        [ 85

In [68]:
def scale(image, label):
  return image/255, label

In [69]:
train_ds = train_ds.map(scale)

In [70]:
for image,label in train_ds.take(5):
  print("image: ",image.numpy()[0][0])
  print("label: ", label.numpy())

image:  [0.2133272  0.26822916 0.27215073]
label:  b'f1_car'
image:  [0.42352942 0.54509807 0.7254902 ]
label:  b'f1_car'
image:  [0.04313726 0.05882353 0.23529412]
label:  b'f1_car'
image:  [0.43884805 0.46237746 0.46237746]
label:  b'f1_car'
image:  [0.1343099  0.23627068 0.08332951]
label:  b'f1_car'


In [71]:
image_ds = tf.data.Dataset.list_files('/content/drive/MyDrive/dataset_images/*/*', shuffle =False)

In [73]:
image_count = len(image_ds)
image_count

199

In [74]:
train_size = int(image_count*0.8)

train_ds = image_ds.take(train_size)
test_ds = image_ds.skip(train_size)

In [75]:
train_ds = train_ds.map(process_image).map(scale)

In [76]:
for image,label in train_ds.take(5):
  print("image: ",image.numpy()[0][0])
  print("label: ", label.numpy())

image:  [0.2133272  0.26822916 0.27215073]
label:  b'f1_car'
image:  [0.42352942 0.54509807 0.7254902 ]
label:  b'f1_car'
image:  [0.04313726 0.05882353 0.23529412]
label:  b'f1_car'
image:  [0.43884805 0.46237746 0.46237746]
label:  b'f1_car'
image:  [0.1343099  0.23627068 0.08332951]
label:  b'f1_car'
